name: testapp
description: Allows clients to find photographers and sign up for a photo session with them.

version: 0.0.3+14

environment:
  sdk: ">=2.10.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter
  # Functional programming
  dartz: ^0.9.2
  flutter_bloc: ^6.1.1
  # Localization
  intl: ^0.16.1
  intl_translation: ^0.17.10+1
  # Service locator
  get_it: ^5.0.4
  # Auto router
  auto_route: ^0.6.9
  # Logging
  logging: ^0.11.4
  # Images
  flutter_svg: ^0.19.1


  # Network
  retrofit: ^1.3.4+1
  # Flutter Secure Storage
  flutter_secure_storage: ^3.3.5
  json_serializable: ^3.5.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  # Build runner (for code generation)
  build_runner: any
  lint: ^1.3.0
  # For DI container
  injectable: ^1.0.7
  injectable_generator: ^1.0.5
  # Autoroute generator
  auto_route_generator: ^0.6.9
  # Freezed Generator
  freezed: ^0.12.2
  freezed_annotation: ^0.12.0
  # Json serializable for Freezed
  json_serializable: ^3.5.1
  # Annotation for json_serializable
  json_annotation: ^3.1.1
  # Network
  retrofit_generator: ^1.4.0+2

flutter:
  uses-material-design: true
  assets:
    # Assets
    - assets/icons/check.svg
    - assets/icons/question.svg

  fonts:
    - family: CustomIcons
      fonts:
        - asset: assets/fonts/CustomIcons.ttf
    - family: Ubuntu
      fonts:
        - asset: assets/fonts/Ubuntu-Regular.ttf
        # Normal / regular / plain 400
        - asset: assets/fonts/Ubuntu-Regular.ttf
          weight: 400
        # Light 300
        - asset: assets/fonts/Ubuntu-Light.ttf
          weight: 300
        # Extra-light 200
        - asset: assets/fonts/Ubuntu-Light.ttf
          weight: 200
        # Thin, the least thick 100
        - asset: assets/fonts/Ubuntu-Light.ttf
          weight: 100
        # Light 300
        - asset: assets/fonts/Ubuntu-LightItalic.ttf
          weight: 300
          style: italic
        # Extra-light 200
        - asset: assets/fonts/Ubuntu-LightItalic.ttf
          weight: 200
          style: italic
        # Thin, the least thick 100
        - asset: assets/fonts/Ubuntu-LightItalic.ttf
          weight: 100
          style: italic
        # Medium 500
        - asset: assets/fonts/Ubuntu-Medium.ttf
          weight: 500
        # Medium
        - asset: assets/fonts/Ubuntu-MediumItalic.ttf
          weight: 500
          style: italic
        # Semi-bold 600
        - asset: assets/fonts/Ubuntu-Medium.ttf
          weight: 600
        # Semi-bold 600
        - asset: assets/fonts/Ubuntu-MediumItalic.ttf
          weight: 600
          style: italic
        # Bold 700
        - asset: assets/fonts/Ubuntu-Bold.ttf
          weight: 700
        # Bold 700
        - asset: assets/fonts/Ubuntu-BoldItalic.ttf
          weight: 700
          style: italic
        # Extra-bold 800
        - asset: assets/fonts/Ubuntu-Bold.ttf
          weight: 800
        # Extra-bold 800
        - asset: assets/fonts/Ubuntu-BoldItalic.ttf
          weight: 800
          style: italic
        # Black, the most thick 900
        - asset: assets/fonts/Ubuntu-Bold.ttf
          weight: 900
        # Black, the most thick 900
        - asset: assets/fonts/Ubuntu-BoldItalic.ttf
          weight: 900
          style: italic

    - family: SourceSansPro
      fonts:
        - asset: assets/fonts/SourceSansPro-Regular.otf
        # Normal / regular / plain 400
        - asset: assets/fonts/SourceSansPro-Regular.otf
          weight: 400
        # Light 300
        - asset: assets/fonts/SourceSansPro-Light.otf
          weight: 300
        # Extra-light 200
        - asset: assets/fonts/SourceSansPro-ExtraLight.otf
          weight: 200
        # Thin, the least thick 100
        - asset: assets/fonts/SourceSansPro-ExtraLight.otf
          weight: 100
        # Light 300
        - asset: assets/fonts/SourceSansPro-LightIt.otf
          weight: 300
          style: italic
        # Extra-light 200
        - asset: assets/fonts/SourceSansPro-ExtraLightIt.otf
          weight: 200
          style: italic
        # Thin, the least thick 100
        - asset: assets/fonts/SourceSansPro-ExtraLightIt.otf
          weight: 100
          style: italic
        # Medium 500
        - asset: assets/fonts/SourceSansPro-Regular.otf
          weight: 500
        # Medium
        - asset: assets/fonts/SourceSansPro-It.otf
          weight: 500
          style: italic
        # Semi-bold 600
        - asset: assets/fonts/SourceSansPro-SemiBold.otf
          weight: 600
        # Semi-bold 600
        - asset: assets/fonts/SourceSansPro-SemiBoldIt.otf
          weight: 600
          style: italic
        # Bold 700
        - asset: assets/fonts/SourceSansPro-Bold.otf
          weight: 700
        # Bold 700
        - asset: assets/fonts/SourceSansPro-BoldIt.otf
          weight: 700
          style: italic
        # Extra-bold 800
        - asset: assets/fonts/SourceSansPro-Bold.otf
          weight: 800
        # Extra-bold 800
        - asset: assets/fonts/SourceSansPro-BoldIt.otf
          weight: 800
          style: italic
        # Black, the most thick 900
        - asset: assets/fonts/SourceSansPro-Black.otf
          weight: 900
        # Black, the most thick 900
        - asset: assets/fonts/SourceSansPro-BlackIt.otf
          weight: 900
          style: italic

    - family: JosefinSans
      fonts:
        - asset: assets/fonts/JosefinSans-Regular.ttf
        # Normal / regular / plain 400
        - asset: assets/fonts/JosefinSans-Regular.ttf
          weight: 400
        # Light 300
        - asset: assets/fonts/JosefinSans-Light.ttf
          weight: 300
        # Extra-light 200
        - asset: assets/fonts/JosefinSans-Light.ttf
          weight: 200
        # Thin, the least thick 100
        - asset: assets/fonts/JosefinSans-Thin.ttf
          weight: 100
        # Light 300
        - asset: assets/fonts/JosefinSans-LightItalic.ttf
          weight: 300
          style: italic
        # Extra-light 200
        - asset: assets/fonts/JosefinSans-LightItalic.ttf
          weight: 200
          style: italic
        # Thin, the least thick 100
        - asset: assets/fonts/JosefinSans-ThinItalic.ttf
          weight: 100
          style: italic
        # Medium 500
        - asset: assets/fonts/JosefinSans-Regular.ttf
          weight: 500
        # Medium
        - asset: assets/fonts/JosefinSans-Italic.ttf
          weight: 500
          style: italic
        # Semi-bold 600
        - asset: assets/fonts/JosefinSans-SemiBold.ttf
          weight: 600
        # Semi-bold 600
        - asset: assets/fonts/JosefinSans-SemiBoldItalic.ttf
          weight: 600
          style: italic
        # Bold 700
        - asset: assets/fonts/JosefinSans-Bold.ttf
          weight: 700
        # Bold 700
        - asset: assets/fonts/JosefinSans-BoldItalic.ttf
          weight: 700
          style: italic
        # Extra-bold 800
        - asset: assets/fonts/JosefinSans-Bold.ttf
          weight: 800
        # Extra-bold 800
        - asset: assets/fonts/JosefinSans-BoldItalic.ttf
          weight: 800
          style: italic
        # Black, the most thick 900
        - asset: assets/fonts/JosefinSans-Bold.ttf
          weight: 900
        # Black, the most thick 900
        - asset: assets/fonts/JosefinSans-BoldItalic.ttf
          weight: 900
          style: italic
